/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideNavComponent: typeof import('./src/components/aside/AsideNavComponent.vue')['default']
    AuthComponent: typeof import('./src/components/auth/AuthComponent.vue')['default']
    AuthFormComponent: typeof import('./src/components/auth/AuthFormComponent.vue')['default']
    ChangeColorThemeList: typeof import('./src/components/settings/ChangeColorThemeList.vue')['default']
    ChangeFontView: typeof import('./src/components/settings/ChangeFontView.vue')['default']
    ChangePassword: typeof import('./src/components/settings/ChangePassword.vue')['default']
    ContainerBase: typeof import('./src/components/shared/ContainerBase.vue')['default']
    CreateNoteComponent: typeof import('./src/components/notes/CreateNoteComponent.vue')['default']
    DesktopHeader: typeof import('./src/components/header/DesktopHeader.vue')['default']
    DialogComponent: typeof import('./src/components/shared/DialogComponent.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputTag: typeof import('element-plus/es')['ElInputTag']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ForgotPassword: typeof import('./src/components/auth/ForgotPassword.vue')['default']
    GoogleBlock: typeof import('./src/components/shared/GoogleBlock.vue')['default']
    HeaderChildren: typeof import('./src/components/header/HeaderChildren.vue')['default']
    HeadingComponent: typeof import('./src/components/shared/HeadingComponent.vue')['default']
    ListNotesComponent: typeof import('./src/components/notes/ListNotesComponent.vue')['default']
    LogoComponent: typeof import('./src/components/shared/LogoComponent.vue')['default']
    MainFormElements: typeof import('./src/components/auth/MainFormElements.vue')['default']
    MenuBar: typeof import('./src/components/notes/MenuBar.vue')['default']
    NoteListSkeleton: typeof import('./src/components/skeletons/NoteListSkeleton.vue')['default']
    NotesInformBlock: typeof import('./src/components/notes/NotesInformBlock.vue')['default']
    NotesMoveList: typeof import('./src/components/shared/NotesMoveList.vue')['default']
    NotesPart: typeof import('./src/components/notes/NotesPart.vue')['default']
    RadioSharedStyle: typeof import('./src/components/settings/RadioSharedStyle.vue')['default']
    ResetPassword: typeof import('./src/components/auth/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/shared/SearchComponent.vue')['default']
    SettingsVariations: typeof import('./src/components/settings/SettingsVariations.vue')['default']
    StyleList: typeof import('./src/components/settings/StyleList.vue')['default']
    TagsList: typeof import('./src/components/shared/TagsList.vue')['default']
    TagsListSkeleton: typeof import('./src/components/skeletons/TagsListSkeleton.vue')['default']
    TextBlock: typeof import('./src/components/shared/TextBlock.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
